### PR TITLE
feat: add pagination to plp

### PR DESCRIPTION
**Pull request by darocha**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by WojtekTheWebDev** [comment]
Just a comment for now, tests are failing, @darocha can you take a look why?

**Review by scernisevs — APPROVED** [review]
LGTM :)

**Review by scernisevs — CHANGES_REQUESTED** [review]
hi @darocha , thank you very much for the PR, it looks good to me but tests are failing, could you please have a look at those? :)

**Review by WojtekTheWebDev — APPROVED** [review]
LGTM

**Review by scernisevs — APPROVED** [review]

**Pull request merged**
