### PR TITLE
feat: add context for composables

### PR DESCRIPTION
**Pull request by WojtekTheWebDev**
BigCommerce context added for composables

## Description
BigCommerce context added for composables

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by WojtekTheWebDev** [comment]
PR includes previous changes that has been merged already

**Review by zoltantakacs-born — COMMENTED** [review]
@vue-storefront/bigcommerce-api already defines the type for context. Doesn't this use the same type and could be imported from that package? Or do I missing something?

**Comment by WojtekTheWebDev** [comment]
> @vue-storefront/bigcommerce-api already defines the type for context. Doesn't this use the same type and could be imported from that package? Or do I miss something?

@zoltantakacs-born This context refers to the composables and it differs with CLIENT and CONFIG. ContextualizedEndpoints are common for both of them

**Review by zoltantakacs-born — APPROVED** [review]

**Review by darocha — APPROVED** [review]
All looks good.

**Pull request merged**
