### PR TITLE
feat: assign the cart to the logged-in user

### PR DESCRIPTION
**Pull request by zoltantakacs-born**
The cart should be assigned to the user after login. After logout the cart should be dropped and a new guest cart created. The user cart should be persistent between sessions. Clearing the cart as a logged-in user creates a new user cart.

## Related Issue
VBC-70

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by darocha — APPROVED** [review]
Zoltan, great work!

**Review by dhargitai — APPROVED** [review]
Looks good to me 👍

**Review by WojtekTheWebDev — APPROVED** [review]
LGTM

**Review by scernisevs — APPROVED** [review]
LGTM thank you very much Zoltan :)

**Pull request merged**
